// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// ...


/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgz5IXELI8O3LWwoUjrnjMHUZ1wuYpJj0',
    appId: '1:380009928296:android:4bb5f4ed41e73bc4034ddd',
    messagingSenderId: '380009928296',
    projectId: 'healthapp-4107c',
    storageBucket: 'healthapp-4107c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY6uSfzMM-bIZgrNFB2310RxyZZU2j4pY',
    appId: '1:380009928296:ios:b0dac7afc565748b034ddd',
    messagingSenderId: '380009928296',
    projectId: 'healthapp-4107c',
    storageBucket: 'healthapp-4107c.appspot.com',
    iosClientId: '380009928296-ch9egofcr55ra583nbturco4d7mj2597.apps.googleusercontent.com',
    iosBundleId: 'com.example.boykiloindeks',
  );
}
